# Lab 10 (NumPy Arrays)

Course: Artificial Intelligence (BS CS(`Evening`))

Name: **Muhammad Asif**

Instructor: **Mr. Azeem Aslam**

Roll No: 2024-csre-008

Week: 10 – `NumPy Arrays`, `Indexing`, `Slicing`, `Operations`

Date: **21-11-25**

Lab Type: Hands-on Python / Jupyter Lab (Concepts + Coding)

**Lab Objective**: In this lab we will first understand the concepts in simple words, then write code. By the end of this lab, students should be able to:
Explain what NumPy and arrays are in their own words.
Create 1D and 2D arrays using different NumPy functions.
Use indexing and slicing on 1D and 2D arrays.
Apply arithmetic and basic statistics on arrays.
Relate these ideas to AI datasets and features.

# Part 1 – What is NumPy and Why Do We Use It?

**Concept in Simple Words**:
In AI, we work with a lot of numbers: image pixels, exam marks, sensor values, probabilities, etc. If we use only Python lists, things become slow and code becomes long.

**NumPy** is a Python library that gives us:
- A special data type called array **(ndarray)**.
- Fast mathematical operations on whole arrays (no loops needed in many cases).
- Functions for statistics, linear algebra, random numbers, etc.
- In short: NumPy is the “math engine” behind many AI/ML librarie

### 1.1 – Importing NumPy

In [1]:
import numpy as np

print("NumPy version:", np.__version__)

NumPy version: 2.1.3


# Part 2 – Creating NumPy Arrays

**Array** vs **List** (Idea Only):
- **List** is a general container. It can store different types (int, string, float together).
- **Array** in NumPy is more strict: usually one data type (all int or all float).
- Because of same type and contiguous memory, NumPy arrays are much faster and support vectorised operations.
- For AI datasets (features, labels, images), we almost always use NumPy arrays.

### 2.1 – Creating Array from Python List

In [2]:
import numpy as np

# Python list
marks_list = [45, 60, 72, 88]

# Convert to NumPy array
marks_array = np.array(marks_list)

print("List:", marks_list)
print("Array:", marks_array)
print("Type of list:", type(marks_list))
print("Type of array:", type(marks_array))

List: [45, 60, 72, 88]
Array: [45 60 72 88]
Type of list: <class 'list'>
Type of array: <class 'numpy.ndarray'>


### Lab Task 2A (5 minutes):
- Create a list of 5 temperatures in Celsius (for example [22, 25, 28, 30, 27]).
- Convert it to a NumPy array using np.array() and print it.
- Print the type of the array (should show numpy.ndarray).

In [6]:
# Python list
temperatures = [22, 25, 28, 30, 27]

# Convert to NumPy array
celcius = np.array(temperatures)
print(celcius)
print(type(celcius))

[22 25 28 30 27]
<class 'numpy.ndarray'>


### 2.2 – Using np.arange and np.linspace

In [7]:
# np.arange(start, stop, step)
a = np.arange(0, 10, 2)
print("arange array:", a)

# np.linspace(start, stop, num_of_values)
b = np.linspace(0, 1, 5)
print("linspace array:", b)

arange array: [0 2 4 6 8]
linspace array: [0.   0.25 0.5  0.75 1.  ]


### Lab Task 2B (10 minutes):
- Create an array of all even numbers from 2 to 20 using np.arange.
- Create an array of 6 values between 5 and 10 using np.linspace.
- In your notebook, write one possible AI use-case for each (e.g., threshold ranges, time steps, feature ranges).

In [8]:
# np.arange(start, stop, step)
a = np.arange(2, 20, 2)
print("arange array:", a)

# np.linspace(start, stop, num_of_values)
b = np.linspace(5, 10, 6)
print("linspace array:", b)

arange array: [ 2  4  6  8 10 12 14 16 18]
linspace array: [ 5.  6.  7.  8.  9. 10.]


###  2.3 – Zeros, Ones and Random Arrays

#### Why zeros, ones and random?
- **zeros** – when we need an empty matrix to fill later (e.g., feature table).
- **ones** – when we need default values (e.g., bias terms, placeholders).
- **random** – when we simulate data or initialise model weights randomly.

In [9]:
zeros_arr = np.zeros((3, 3))     # 3x3 matrix of zeros
ones_arr  = np.ones((2, 4))      # 2x4 matrix of ones
rand_arr  = np.random.rand(2, 3) # 2x3 matrix of random numbers (0 to 1)

print("Zeros:\n", zeros_arr)
print("Ones:\n", ones_arr)
print("Random:\n", rand_arr)

Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Ones:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Random:
 [[0.3115965  0.03416573 0.04575103]
 [0.34662126 0.82721498 0.791774  ]]


### Lab Task 2C (10 minutes):
- Create a 4x4 zeros array and imagine it as “empty feature matrix for 4 students and 4 features”.
- Create a 3x2 ones array and think of it as “default feature = 1” for some binary flags.
- Create a 5-element random array. Print it and write: “This could be random initial weights”.

In [12]:
zeros_arr = np.zeros((4, 4))     # 4x4 matrix of zeros
ones_arr  = np.ones((3, 2))      # 3x2 matrix of ones
rand_arr  = np.random.rand(1, 5) # 1x5 matrix of random numbers (0 to 1)

print("Zeros:\n", zeros_arr)
print("Ones:\n", ones_arr)
print("Random:\n", rand_arr)

Zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
Random:
 [[0.9674873  0.03317955 0.6788516  0.64684612 0.5221419 ]]


# Part 3 – Indexing & Slicing (1D and 2D)

##### Why indexing and slicing?
In AI, our data is often stored in big matrices: rows = samples, columns = features. We rarely use the whole matrix at once. We need:
- Specific element (one value).
- One full row (one data sample).
- One full column (one feature).
- Small sub-matrix (mini-batch).

Indexing and slicing give us this power.

### 3.1 – 1D Array Indexing and Slicing

**Concept:**
A 1D array is like a line of values: [10, 20, 30, 40, 50].
Indexing uses:
- arr[0] → first element
- arr[-1] → last element (negative index counts from end)

Slicing uses arr[start:end:step] (end is not included).

In [14]:
arr = np.array([10, 20, 30, 40, 50])

print(arr[0])     # first element  (10)
print(arr[2])     # third element  (30)
print(arr[-1])    # last element   (50)

# slicing: arr[start:end]  (end is not included)
print(arr[1:4])   # [20 30 40]
print(arr[:3])    # [10 20 30]
print(arr[2:])    # [30 40 50]
print(arr[::2])   # [10 30 50]  step = 2

10
30
50
[20 30 40]
[10 20 30]
[30 40 50]
[10 30 50]


#### Lab Task 3A (10 minutes):
- Create a = np.array([5, 10, 15, 20, 25, 30]).
- Print: First element using a[0].
- Last two elements using slicing.
- Every second element (step = 2).

In notebook, write: “What does a[1:4] give?” and check by printing.

**ANS**:

[1:4] give us element from 1 index to 4 index which is [10, 15, 20, 25].

In [18]:
arr = np.array([5, 10, 15, 20, 25, 30])

print(arr[0])     # first element  (5)


# slicing: arr[start:end]  (end is not included)
print(arr[4:])
print(arr[1:4])    

5
[25 30]
[10 15 20]


#### 3.2 – 2D Arrays (Matrix) Indexing

In [19]:
m = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print("Matrix:\n", m)

# element at row 0, column 1
print("m[0, 1] =", m[0, 1])  # 2

# second row (index 1)
print("Row 1:", m[1, :])     # [4 5 6]

# third column (index 2)
print("Column 2:", m[:, 2])  # [3 6 9]

# sub-matrix (top-left 2x2)
print("Sub-matrix:\n", m[0:2, 0:2])

Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
m[0, 1] = 2
Row 1: [4 5 6]
Column 2: [3 6 9]
Sub-matrix:
 [[1 2]
 [4 5]]


#### 4.1 – Arithmetic with Scalars

**Concept:**
  
A scalar is a single number (like 2, 10, 0.5). When we add/multiply a scalar to an array, it happens for all elements.

In [26]:
arr = np.array([1, 2, 3, 4])

print("arr + 10 =", arr + 10)   # [11 12 13 14]
print("arr * 2  =", arr * 2)    # [2 4 6 8]
print("arr ** 2 =", arr ** 2)   # [1 4 9 16]
print("arr / 2  =", arr / 2)    # [0.5 1.  1.5 2. ]

arr + 10 = [11 12 13 14]
arr * 2  = [2 4 6 8]
arr ** 2 = [ 1  4  9 16]
arr / 2  = [0.5 1.  1.5 2. ]


### Lab Task 4A (10 minutes):

Create:

- marks = np.array([40, 55, 63, 72, 90]).
- Increase every mark by 5 bonus marks using marks + 5.
    
In notebook, write: “If marks are out of 100, what does marks / 100 represent?”

In [28]:
marks = np.array([40, 55, 63, 72, 90])
print("Marks is increased by 5",marks+5)

Marks is increased by 5 [45 60 68 77 95]


#### 4.2 – Element-wise Operations Between Arrays

In [29]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("a + b =", a + b)    # [5 7 9]
print("a * b =", a * b)    # [4 10 18]

a + b = [5 7 9]
a * b = [ 4 10 18]


**Lab Task 4B (10 minutes):**

Create:
- x = np.array([2, 4, 6, 8])
- y = np.array([1, 3, 5, 7])

Compute:
- x + y
- x - y
- x * y

Write one sentence: “This could represent combining two feature arrays in AI because …”

In [32]:
x = np.array([2, 4, 6, 8])
y = np.array([1, 3, 5, 7])

print("Addition",x+y)
print("Subtraction",x-y)
print("Multiplication",x*y)

Addition [ 3  7 11 15]
Subtraction [1 1 1 1]
Multiplication [ 2 12 30 56]


### 4.3 – Basic Statistics: min, max, mean

**Concept:**

Before training an AI model, we often check:
- Minimum value – is it too small / error?
- Maximum value – is there any outlier?
- Mean – average value used in normalisation.

NumPy gives direct functions for this.

In [34]:
data = np.array([10, 20, 35, 40, 50])

print("Min:", np.min(data))
print("Max:", np.max(data))
print("Mean:", np.mean(data))

Min: 10
Max: 50
Mean: 31.0


**Lab Task 4C (10 minutes):**

Create random marks:
- arr = np.random.randint(0, 101, size=8)

Print:
- Minimum
- Maximum
- Average (mean)

In notebook, answer: “Why is mean useful before training a model?”

In [36]:
arr = np.random.randint(0, 101, size=8)

print("Min:", np.min(arr))
print("Max:", np.max(arr))
print("Mean:", np.mean(arr))

Min: 10
Max: 91
Mean: 59.75


# Part 5 – Mini Exercise: Simple Data Cleaning for A

**Concept:**
Real-world data often has wrong values (outliers). 

**Example**: sensor reading suddenly jumps to 9999 or -100. These can break our model. One simple approach:
- Find “normal” range.
- Replace very large/small values with a safe value like mean.

This is not the only method but a basic idea for beginners.

In [54]:
import numpy as np

# Simulated data values
values = np.array([15, 16, 200, 17, 16, 400, 15, 18])

print("Original values:", values)

# Step 1: Find mean and standard deviation
mean_val = np.mean(values)
std_val  = np.std(values)

print("Mean:", mean_val)
print("Std: ", std_val)

# Step 2: Replace very large values (> 100) with mean
cleaned = np.where(values > 50, mean_val, values)

print("Cleaned values:", cleaned)

Original values: [ 15  16 200  17  16 400  15  18]
Mean: 87.125
Std:  132.6880151897676
Cleaned values: [15.    16.    87.125 17.    16.    87.125 15.    18.   ]
